  # Step 4: Terraform plan policy enforcement
  - id: conftest-tf
    name: openpolicyagent/conftest:latest
    entrypoint: sh
    args:
      - -c
      - |
        echo "Running Terraform plan policy tests..."
        test -f tfplan.json || (echo "tfplan.json missing" && exit 1)
        conftest test -p policy/tf tfplan.json
